apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: {{ .Values.mongo.containerPort }}
    targetPort: {{ .Values.mongo.containerPort }}
