apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: 1Gi
  accessModes:
  - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
