apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
  - port: {{ .Values.springapp.servicePort }}
    targetPort: {{ .Values.springapp.containerPort }}
